name: r2r-robosuite
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - astunparse=1.6.3
  - attrs=25.3.0
  - autobahn=24.4.2
  - automat=25.4.16
  - bcrypt=3.2.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.9
  - cffi=1.15.0
  - charset-normalizer=3.4.2
  - click=8.2.1
  - cmake=3.21.3
  - colorama=0.4.6
  - constantly=15.1.0
  - cryptography=45.0.3
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-nvcc-tools=12.4.131
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.4.131
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - expat=2.4.8
  - flatbuffers=24.3.25
  - gast=0.5.3
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.62.2
  - hdf5=1.14.5
  - hkdf=0.0.3
  - humanize=4.12.3
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - incremental=24.7.2
  - iterable-io=1.0.0
  - jpeg=9e
  - keras=3.6.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurand=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libnvjitlink=12.4.127
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libuv=1.43.0
  - libxcb=1.17.0
  - lz4-c=1.9.3
  - magic-wormhole=0.19.2
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - ml_dtypes=0.4.1
  - mpi=1.0
  - mpi4py=3.1.3
  - mpich=4.0.2
  - namex=0.0.7
  - nccl=2.21.5.1
  - ncurses=6.4
  - ninja=1.11.0
  - openssl=3.0.16
  - opt_einsum=3.3.0
  - optree=0.14.1
  - packaging=25.0
  - pip=25.1.1
  - portalocker=3.0.0
  - pthread-stubs=0.4
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pynacl=1.5.0
  - pyopenssl=25.1.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-flatbuffers=24.3.25
  - python_abi=3.10
  - qrcode=8.2
  - re2=2022.04.01
  - readline=8.2
  - rhash=1.4.1
  - rich=13.9.4
  - service-identity=24.2.0
  - service_identity=24.2.0
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - spake2=0.9
  - sqlite=3.45.3
  - tensorboard=2.17.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=3.1.0
  - tk=8.6.14
  - tomli=2.2.1
  - tqdm=4.67.1
  - transforms3d=0.4.2
  - twisted=22.4.0
  - txaio=25.6.1
  - txtorcon=24.8.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zipstream-ng=1.8.0
  - zlib=1.2.13
  - zope.interface=5.4.0
  - zstd=1.5.0
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - array-record==0.7.2
      - asttokens==3.0.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - certifi==2025.4.26
      - chardet==5.2.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.0.4
      - decorator==5.2.1
      - dm-tree==0.1.9
      - docstring-parser==0.16
      - egl-probe==1.0.2
      - einops==0.8.1
      - etils==1.12.2
      - evdev==1.9.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.0.3
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gdown==5.2.0
      - glfw==2.9.0
      - gputil==1.4.0
      - h5py==3.13.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - ipython==8.36.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - markdown==3.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - mujoco==2.3.2
      - narwhals==1.38.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - plotly==6.0.1
      - prettytable==3.16.0
      - promise==2.3
      - prompt-toolkit==3.0.51
      - protobuf==4.21.12
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pygments==2.19.1
      - pynput==1.8.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.3.4
      - robosuite==1.4.1
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - simple-parsing==0.1.7
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow-datasets==4.9.9
      - tensorflow-metadata==1.17.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.7.0
      - torchvision==0.22.0
      - traitlets==5.14.3
      - triton==3.3.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zipp==3.21.0
