
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiserver.py --connection --connection_num 3 --port 61231 --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --source_robot Sawyer  --source_gripper RethinkGripper --start_id 0 &
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiclient.py --connection --port 61231  --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --target_robot Panda  --target_gripper PandaGripper --start_id 0 &
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiclient.py --connection --port 61231  --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --target_robot UR5e --target_gripper Robotiq85Gripper --start_id 0 &
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiclient.py --connection --port 61231  --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --target_robot Jaco --target_gripper JacoThreeFingerGripper --start_id 0 &

sleep 10


CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiserver.py --connection --connection_num 3 --port 61232 --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --source_robot Sawyer  --source_gripper RethinkGripper --start_id 0 &
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiclient.py --connection --port 61232 --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --target_robot Panda  --target_gripper PandaGripper --start_id 0 &
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiclient.py --connection --port 61232 --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --target_robot UR5e --target_gripper Robotiq85Gripper --start_id 0 &
CUDA_VISIBLE_DEVICES=4 python paired_images_data_gen_multiclient.py --connection --port 61232  --num_cam_poses_per_robot_pose 5 --save_paired_images_folder_path data/franka_ur5_sawyer_jaco_open_gripper/paired_images_roboturk --robot_dataset roboturk --target_robot Jaco --target_gripper JacoThreeFingerGripper --start_id 0 